[package]
name = "arpc_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.38", features = ["full"] }
quote = "1.0.33"
proc-macro2 = "1.0.69"
convert_case = "0.6.0"
