[workspace]

resolver = "2"

members = [
  "early-init",
  "fs-server",
  "hwaccess-server",
  "arpc",
  "arpc_derive",
  "aser",
  "asynca",
  "aurora",
  "aurora_core",
  "bit_utils",
  "std",
  "sys",
]
