use core::arch::asm;

extern "C" {
    fn main() -> !;
}

#[naked]
#[no_mangle]
pub extern "C" fn _aurora_startup() {
    unsafe {
        asm!(
            "pop rdi",
            "call _rust_startup",
            options(noreturn)
        )
    }
}

#[no_mangle]
pub extern "C" fn _rust_startup(_startup_data: usize) -> ! {
    unsafe {
        // main is function generated by rust compiler which calls the start lang item
        // it is used only to resolve actual rust main method, it does not perform any other startup actions
        main()
    }
}